export const marketplaceConfig = {
  routes: {
    "/marketplace": "marketplace",
    "/login": "login",
    "/register": "register",
    "/forgot-password": "forgot",
    "/reset-password": "reset",
    "/member": "member",
    "/member/profile": "profile",
    "/member/notifications": "notifications",
    "/member/orders": "orders",
    "/member/consultation": "consultation",
    "/admin": "admin",
    "/admin/consultation": "admin-consultation",
    "/admin/orders": "admin-orders",
    "/admin/products": "admin-products",
    "/news": "news",
    "/checkout": "checkout",
  },
  titles: {
    marketplace: "Mini Marketplace",
    product: "Detail Produk",
    login: "Login Member",
    register: "Register Member",
    forgot: "Lupa Password",
    reset: "Reset Password",
    member: "Member Dashboard",
    profile: "Profile Settings",
    notifications: "Notification Center",
    orders: "Order History",
    consultation: "IT Consultation",
    admin: "Admin Dashboard",
    "admin-consultation": "Admin Consultation Queue",
    "admin-orders": "Admin Order Monitoring",
    "admin-products": "Admin Product Management",
    article: "Feira IT Article",
    news: "Feira IT News",
    checkout: "Checkout",
  },
};
